trigger:
- '*'

variables:
  buildConfiguration: 'Release'
  webRepository: 'web'
  tag: '$(Build.BuildId)'

stages:
  - stage: 'Build'
    displayName: 'Build and push'
    jobs:  
    - job: 'Build'
      displayName: 'Build job'
      pool:
        vmImage: 'ubuntu-20.04'
      steps:
      - task: PowerShell@2
        displayName: 'Build and push the image to container registry'
        inputs:
          script: |
            docker build -t $(webRepository):$(tag) $(Build.Repository.LocalPath)
            docker push $(webRepository):$(tag)

  - stage: 'Deploy'
    displayName: 'Deploy the container'
    dependsOn: Build
    jobs:
    - job: 'Deploy'
      displayName: 'Deploy job'
      pool:
        vmImage: 'ubuntu-20.04'
      variables:
      - group: Release
      steps:
      - task: AzureWebAppContainer@1
        inputs:
          appName: $(WebAppName)
          azureSubscription: 'Resource Manager - Tailspin - Space Game2'
          imageName: $(RegistryName)/$(webRepository):$(build.buildId)
      - task: PowerShell@2
